server:
  port: 6868
  servlet:
    context-path: /api/v1

spring:
  application:
    name: student-management

  profiles:
    default: dev

  security:
    jwt:
      expiration-seconds: 3600

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false