server:
  port: 6868
  servlet:
    context-path: /api/v1

spring:
  application:
    name: student-management

  profiles:
    default: dev

  security:
    jwt:
      expiration-seconds: 3600

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM:${MAIL_USERNAME}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

minio:
  url: ${MINIO_URL:http://localhost:${MINIO_PORT:9000}}
  public-url: ${MINIO_PUBLIC_URL:${MINIO_SERVER_URL:${MINIO_URL:http://localhost:${MINIO_PORT:9000}}}}
  access-key: ${MINIO_ACCESS_KEY:${MINIO_ROOT_USER:minioadmin}}
  secret-key: ${MINIO_SECRET_KEY:${MINIO_ROOT_PASSWORD:minioadmin}}
  bucket: ${MINIO_BUCKET:${MINIO_BUCKET_NAME:student-management}}

app:
  name: ${APP_NAME:Student Management}
  frontend-url: ${APP_FRONTEND_URL:http://localhost:5173}
  backend-url: ${APP_BACKEND_URL:http://localhost:6868/api/v1}

# logging:
#   level:
#     org.springframework.mail: DEBUG
#     org.eclipse.angus.mail: DEBUG # Vì log của bạn dùng angus-mail